//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace itog
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PPEntities : DbContext
    {
        private static PPEntities _context;
        public PPEntities()
            : base("name=PPEntities")
        {
        }
        public static PPEntities GetContext()
        {
            if (_context == null)
                _context = new PPEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cabinet> Cabinet { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Classification> Classification { get; set; }
        public virtual DbSet<Education> Education { get; set; }
        public virtual DbSet<Kid> Kid { get; set; }
        public virtual DbSet<Record> Record { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
