//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace itog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int ID { get; set; }
        public string Date { get; set; }
        public string Time_Start { get; set; }
        public int Cabinets { get; set; }
        public int Users { get; set; }
        public int Kids { get; set; }
    
        public virtual Cabinet Cabinet { get; set; }
        public virtual Kid Kid { get; set; }
        public virtual User User { get; set; }
    }
}
